# Generated by Django 3.0.4 on 2021-01-02 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRMmain', '0003_auto_20210102_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM_Zadatha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('chec', models.BooleanField(blank=True, null=True)),
                ('zada', models.TextField(blank=True, null=True)),
                ('prior', models.CharField(blank=True, choices=[('lo', 'Низкий'), ('mi', 'Средний'), ('hi', 'Высокий')], max_length=50, null=True)),
                ('srok', models.DateField(blank=True, max_length=50, null=True)),
                ('otvet', models.CharField(blank=True, max_length=150, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('projects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRMmain.CRM_Lid_Zapros')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
