# Generated by Django 3.0.4 on 2021-01-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMzadacha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_zadatha',
            name='chec_zad',
            field=models.CharField(blank=True, choices=[('nn', 'Не начат'), ('vr', 'В работе'), ('vi', 'Выполненно'), ('nv', 'Не выполненно')], max_length=50, null=True),
        ),
    ]
