# Generated by Django 3.0.4 on 2021-01-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMzadacha', '0002_crm_zadatha_chec_zad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crm_zadatha',
            name='chec_zad',
        ),
        migrations.AlterField(
            model_name='crm_zadatha',
            name='chec',
            field=models.CharField(blank=True, choices=[('nn', 'Не начат'), ('vr', 'В работе'), ('vi', 'Выполненно'), ('nv', 'Не выполненно')], max_length=50, null=True),
        ),
    ]
