# Generated by Django 3.0.4 on 2021-01-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMzadacha', '0003_auto_20210105_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crm_zadatha',
            options={'ordering': ['-modified']},
        ),
    ]
