# Generated by Django 3.0.4 on 2021-01-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMcontacts', '0005_auto_20210101_2300'),
        ('CRMzadacha', '0004_auto_20210109_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_zadatha',
            name='conact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRMcontacts.CRM_Contacts'),
        ),
    ]
