# Generated by Django 3.0.4 on 2021-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMzadacha', '0005_crm_zadatha_conact'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_zadatha',
            name='created_by',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='crm_zadatha',
            name='katigoria',
            field=models.CharField(blank=True, choices=[('za', 'Задача'), ('pi', 'Письмо'), ('zv', 'Звонок'), ('vs', 'Встреча')], max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='crm_zadatha',
            name='napominanie',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ответственному'),
        ),
        migrations.AddField(
            model_name='crm_zadatha',
            name='napominanie_data',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='Дата напоминания'),
        ),
        migrations.AlterField(
            model_name='crm_zadatha',
            name='chec',
            field=models.CharField(blank=True, choices=[('nn', 'Не начат'), ('vr', 'В работе'), ('vi', 'Выполнено'), ('nv', 'Не выполнено')], max_length=50, null=True),
        ),
    ]
