# Generated by Django 3.0.4 on 2021-01-12 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMzadacha', '0006_auto_20210112_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_zadatha',
            name='chec',
            field=models.CharField(blank=True, choices=[('nn', 'Не начат'), ('vr', 'В работе'), ('vi', 'Выполнено'), ('nv', 'Не выполнено')], default='vr', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crm_zadatha',
            name='katigoria',
            field=models.CharField(blank=True, choices=[('za', 'Задача'), ('pi', 'Письмо'), ('zv', 'Звонок'), ('vs', 'Встреча')], default='za', max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='crm_zadatha',
            name='prior',
            field=models.CharField(blank=True, choices=[('lo', 'Низкий'), ('mi', 'Средний'), ('hi', 'Высокий')], default='mi', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crm_zadatha',
            name='srok',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 1, 13), max_length=50, null=True),
        ),
    ]
