# Generated by Django 3.0.4 on 2021-01-12 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMzadacha', '0007_auto_20210112_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_zadatha',
            name='srok',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 1, 14), max_length=50, null=True),
        ),
    ]
