# Generated by Django 3.0.4 on 2021-01-14 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMzadacha', '0008_auto_20210113_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_zadatha',
            name='srok',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 1, 15), max_length=50, null=True),
        ),
    ]
