# Generated by Django 3.0.4 on 2021-01-18 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMzadacha', '0011_crm_zadatha_zakaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_zadatha',
            name='srok',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 1, 20), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crm_zadatha',
            name='title',
            field=models.CharField(blank=True, default='Запрос ', max_length=500, null=True),
        ),
    ]
