# Generated by Django 3.0.4 on 2021-01-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMzakaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_zakaz',
            name='opisanie',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='crm_zakaz',
            name='status',
            field=models.CharField(blank=True, choices=[('ACT', 'В работе'), ('RES', 'Приостановлен'), ('ZVR', 'Завершен')], default='ACT', max_length=10, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='crm_zakaz',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Название'),
        ),
    ]
