# Generated by Django 3.0.4 on 2021-01-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0003_auto_20210102_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM_Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('opisanie', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('filefild', models.FileField(upload_to='file')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('projects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRMmain.CRM_Lid_Zapros')),
            ],
        ),
    ]
