# Generated by Django 3.0.4 on 2021-01-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0005_crm_histori'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_lid_zapros',
            name='prov_na_sklade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
