# Generated by Django 3.0.4 on 2021-01-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0006_crm_lid_zapros_prov_na_sklade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM_Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerpositin', models.CharField(max_length=100, verbose_name='Номер позиции')),
                ('kod_TPL', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ТПЛ')),
                ('izdelie', models.CharField(blank=True, choices=[('SLIT', 'Слитки'), ('LIST', 'Листы'), ('ELIC', 'Электроды'), ('PLIT', 'Плиты'), ('LENT', 'Лента'), ('FOLG', 'Фольга'), ('PRYT', 'Прутки'), ('TRUB', 'Трубы'), ('PRIO', 'Припой')], max_length=10, null=True, verbose_name='Изделие')),
                ('splav', models.CharField(choices=[('1', 'ВТ 1-00'), ('2', 'ВТ 1-0'), ('3', 'ОТ 4-0'), ('4', 'ОТ 4'), ('5', 'ОТ 4-1'), ('6', 'ВТ 3-1'), ('7', 'ВТ 5'), ('8', 'ВТ 5-1'), ('9', 'ВТ 6'), ('10', 'ВТ 6ч'), ('11', 'ВТ 6с'), ('12', 'ВТ 16'), ('13', 'ВТ 18'), ('14', 'ВТ 8,ВТ8-1'), ('15', 'ВТ 9'), ('16', 'ВТ 14'), ('17', 'ВТ 18у'), ('18', 'ВТ 20'), ('19', 'ВТ 22'), ('20', 'ВТ 23'), ('21', 'ВТ 25'), ('22', 'ВТ 25у'), ('23', 'ТС 6'), ('24', 'VST-2')], max_length=10, verbose_name='Cплав')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('projects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRMmain.CRM_Lid_Zapros')),
            ],
        ),
    ]
