# Generated by Django 3.0.4 on 2021-01-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0008_auto_20210109_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_positions',
            name='dlinna_min',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='min'),
        ),
    ]
