# Generated by Django 3.0.4 on 2021-01-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0009_crm_positions_dlinna_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_positions',
            name='izdelie_form',
            field=models.CharField(blank=True, choices=[('SLIT', 'Круглый пруток'), ('LIST', 'Билет'), ('ELIC', 'Слиток')], max_length=10, null=True, verbose_name='Форма изделий'),
        ),
        migrations.AlterField(
            model_name='crm_positions',
            name='izdelie',
            field=models.CharField(blank=True, choices=[('SLIT', 'Слитки'), ('LIST', 'Листы'), ('ELIC', 'Электроды'), ('PLIT', 'Плиты'), ('LENT', 'Лента'), ('FOLG', 'Фольга'), ('PRYT', 'Прутки'), ('TRUB', 'Трубы'), ('PRIO', 'Припой')], max_length=10, null=True, verbose_name='Изделие'),
        ),
    ]
