# Generated by Django 3.0.4 on 2021-01-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0010_auto_20210110_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_lid_zapros',
            name='prov_na_nom',
            field=models.FloatField(blank=True, default=1, max_length=10, null=True),
        ),
    ]
