# Generated by Django 3.0.4 on 2021-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0011_crm_lid_zapros_prov_na_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_lid_zapros',
            name='status',
            field=models.CharField(blank=True, choices=[('ACT', 'В работе'), ('RES', 'Приостановлен'), ('OTC', 'Отказ')], default='ACT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crm_lid_zapros',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
