# Generated by Django 3.0.4 on 2021-01-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0012_auto_20210112_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_lid_zapros',
            name='otkaz_prith',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='crm_lid_zapros',
            name='postavshik',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Поставщик'),
        ),
    ]
