# Generated by Django 3.0.4 on 2021-01-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0013_auto_20210113_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_lid_zapros',
            name='otkaz_tip',
            field=models.CharField(blank=True, choices=[('ACT', 'Неустроила цена '), ('RES', 'Неустроила дата '), ('OTC', 'Отказ')], default='ACT', max_length=10, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='crm_lid_zapros',
            name='otkaz_prith',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
    ]
