# Generated by Django 3.0.4 on 2021-01-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0014_auto_20210113_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_lid_zapros',
            name='otkaz_tip',
            field=models.CharField(choices=[('ACT', 'Неустроила цена '), ('RES', 'Неустроила дата '), ('OTC', 'Отказ')], default='ACT', max_length=10, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='crm_lid_zapros',
            name='status',
            field=models.CharField(blank=True, choices=[('ACT', 'В работе'), ('RES', 'Приостановлен'), ('OTC', 'Отказ'), ('ZVR', 'Завершен')], default='ACT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crm_positions',
            name='diametr_vnut',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Внутренний'),
        ),
        migrations.CreateModel(
            name='CRM_P_Postavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('data', models.DateField(blank=True, null=True)),
                ('ves', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Вес')),
                ('kollitsh', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Кол-во')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('posi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRMmain.CRM_Positions')),
            ],
        ),
    ]
