# Generated by Django 3.0.4 on 2021-01-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0018_crm_lid_zapros_proz_nadb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crm_lid_zapros',
            name='proz_nadb',
        ),
        migrations.AddField(
            model_name='crm_positions',
            name='proz_nadb',
            field=models.FloatField(blank=True, default=1, max_length=10, null=True),
        ),
    ]
