# Generated by Django 3.0.4 on 2021-01-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMmain', '0019_auto_20210114_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_positions',
            name='dop_trebovaniy',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Дополнительные требования'),
        ),
        migrations.AddField(
            model_name='crm_positions',
            name='markirov',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Маркировка'),
        ),
        migrations.AddField(
            model_name='crm_positions',
            name='metod_plav',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Метод плавления'),
        ),
        migrations.AddField(
            model_name='crm_positions',
            name='opred_k_mukr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Определение микроструктуры'),
        ),
        migrations.AddField(
            model_name='crm_positions',
            name='sostoyniy_pov',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Состояние поверхности'),
        ),
        migrations.AddField(
            model_name='crm_positions',
            name='trebov_k_makr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Требования к макроструктуре'),
        ),
        migrations.AddField(
            model_name='crm_positions',
            name='trebov_k_of_sert',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Требования к оформлению сертификатов'),
        ),
        migrations.AddField(
            model_name='crm_positions',
            name='trebovan_US',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Требования по УЗ контролю'),
        ),
        migrations.AlterField(
            model_name='crm_lid_zapros',
            name='otkaz_tip',
            field=models.CharField(choices=[('ACT', 'Изменение приоритетов у клиента '), ('RES', 'Не договорились по сумме'), ('OTC', 'Не договорились по срокам поставки'), ('KLD', 'Клиент отказывается от общения'), ('VBK', 'Выбрали конкурента')], default='ACT', max_length=10, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='crm_positions',
            name='izdelie_form',
            field=models.CharField(blank=True, choices=[('SLIT', 'ОСТ 1-90218-76'), ('LIST', 'ТУ 1-5-093-77'), ('ELIC', 'ГОСТ 22178-76')], max_length=10, null=True, verbose_name='Стандарты'),
        ),
    ]
