# Generated by Django 3.0.4 on 2020-12-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMcontacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_kompani',
            name='opisanie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
