# Generated by Django 3.0.4 on 2020-12-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMcontacts', '0002_crm_kompani_opisanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_kompani',
            name='contru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='siti',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crm_kompani',
            name='opisanie',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
