# Generated by Django 3.0.4 on 2020-12-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMcontacts', '0003_auto_20201230_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_kompani',
            name='kod_ERP',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='kod_WMS',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='registr',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='saits',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='sfera',
            field=models.CharField(blank=True, choices=[('ПО', 'Проектный отчет'), ('НДА', 'NDA')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='tip',
            field=models.CharField(blank=True, choices=[('ПО', 'Проектный отчет'), ('НДА', 'NDA')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='title_eng',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crm_contacts',
            name='doljnost',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crm_contacts',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='crm_contacts',
            name='tel_nomber',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crm_contacts',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crm_kompani',
            name='contru',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crm_kompani',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='crm_kompani',
            name='opisanie',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crm_kompani',
            name='siti',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crm_kompani',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
