# Generated by Django 3.0.4 on 2021-01-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMcontacts', '0005_auto_20210101_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_contacts',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='crm_contacts',
            name='lang',
            field=models.CharField(blank=True, choices=[('E', 'English'), ('R', 'Русский')], default='', max_length=5, null=True, verbose_name='Язык обращения'),
        ),
        migrations.AddField(
            model_name='crm_contacts',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=200, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='crm_contacts',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
