# Generated by Django 3.0.4 on 2021-01-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMcontacts', '0006_auto_20210112_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_kompani',
            name='bank_title',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Банк получателя'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='big',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='data_ogrn',
            field=models.DateField(blank=True, null=True, verbose_name='Дата записи ОГРН'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='deust',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Действует на основании'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='doc_polm',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Документ, подтверждающий наличие полномочий'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='fio_Buh',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='ФИО Бухгалтера'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='fio_Ruc',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='ФИО Руководителя'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='kpp',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='ks',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='ogrn',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='okato',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='ОКАТО'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='okpo',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='okved',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='ОКВЭД'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='ps',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='crm_kompani',
            name='srok_dok',
            field=models.DateField(blank=True, null=True, verbose_name='Срок полномочий, до:'),
        ),
        migrations.AlterField(
            model_name='crm_contacts',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=5, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='crm_kompani',
            name='sfera',
            field=models.CharField(blank=True, choices=[('AVI5', 'Обрабатывающие производства'), ('PRE4', 'Оптовая и розничная торговля'), ('PRE3', 'Добыча полезных ископаемых'), ('PRE2', 'Сельское хозяйство, охота и лесное хозяйство'), ('PRE1', 'Финансовая деятельность'), ('PRE9', 'Государственное управление и обеспечение военной безопасности'), ('PRE8', 'Строительство'), ('PRE7', 'Транспорт и связь'), ('НДА6', 'Производство и распределение электроэнергии,газа и воды'), ('НДА5', 'Образование'), ('НДА4', 'Гостиницы и рестораны'), ('НДА3', 'Здравоохранение и предоставление социальных услуг'), ('НДА2', 'Рыболовство, рыбоводство'), ('НДА1', 'Предоставление услуг по ведению домашнего хозяйства')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crm_kompani',
            name='tip',
            field=models.CharField(blank=True, choices=[('pr', 'Партнер'), ('ps', 'Поставщик'), ('kl', 'Клиент')], max_length=10, null=True),
        ),
    ]
