# Generated by Django 3.0.4 on 2021-01-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMcontacts', '0007_auto_20210112_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_kompani',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Адрес'),
        ),
    ]
